name: Pylint

on: [push]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pandas pytest setuptools docstring
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
